// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var Theme = /* module */[];

function spacing_to_css(param) {
  if (param >= 26868) {
    if (param >= 5994348) {
      if (param >= 5994355) {
        return /* `px */[
                25096,
                4
              ];
      } else {
        return /* `px */[
                25096,
                72
              ];
      }
    } else if (param >= 26875) {
      return /* `px */[
              25096,
              8
            ];
    } else {
      return /* `px */[
              25096,
              48
            ];
    }
  } else if (param !== 109) {
    if (param >= 115) {
      return /* `px */[
              25096,
              16
            ];
    } else {
      return /* `px */[
              25096,
              32
            ];
    }
  } else {
    return /* `px */[
            25096,
            24
          ];
  }
}

var ToCss = /* module */[/* spacing_to_css */spacing_to_css];

function Box(Props) {
  var children = Props.children;
  var p = Props.p;
  var px = Props.px;
  var py = Props.py;
  var pl = Props.pl;
  var pr = Props.pr;
  var pt = Props.pt;
  var pb = Props.pb;
  var paddingTop = pt !== undefined ? pt : (
      py !== undefined ? py : (
          p !== undefined ? p : undefined
        )
    );
  var paddingBottom = pb !== undefined ? pb : (
      py !== undefined ? py : (
          p !== undefined ? p : undefined
        )
    );
  var paddingRight = pr !== undefined ? pr : (
      px !== undefined ? px : (
          p !== undefined ? p : undefined
        )
    );
  var paddingLeft = pl !== undefined ? pl : (
      px !== undefined ? px : (
          p !== undefined ? p : undefined
        )
    );
  var leftResult = Belt_Option.mapWithDefault(paddingLeft, Css.empty(/* [] */0), (function (x) {
          return Css.paddingLeft(spacing_to_css(x));
        }));
  var rightResult = Belt_Option.mapWithDefault(paddingRight, Css.empty(/* [] */0), (function (x) {
          return Css.paddingRight(spacing_to_css(x));
        }));
  var topResult = Belt_Option.mapWithDefault(paddingTop, Css.empty(/* [] */0), (function (x) {
          return Css.paddingTop(spacing_to_css(x));
        }));
  var bottomResult = Belt_Option.mapWithDefault(paddingBottom, Css.empty(/* [] */0), (function (x) {
          return Css.paddingBottom(spacing_to_css(x));
        }));
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    leftResult,
                    /* :: */[
                      rightResult,
                      /* :: */[
                        topResult,
                        /* :: */[
                          bottomResult,
                          /* [] */0
                        ]
                      ]
                    ]
                  ])
            }, children);
}

var make = Box;

exports.Theme = Theme;
exports.ToCss = ToCss;
exports.make = make;
/* Css Not a pure module */
