// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var Theme = /* module */[];

function spacing_to_css(param) {
  if (param >= 26868) {
    if (param >= 5994348) {
      if (param >= 5994355) {
        return /* `px */[
                25096,
                4
              ];
      } else {
        return /* `px */[
                25096,
                72
              ];
      }
    } else if (param >= 26875) {
      return /* `px */[
              25096,
              8
            ];
    } else {
      return /* `px */[
              25096,
              48
            ];
    }
  } else if (param !== 109) {
    if (param >= 115) {
      return /* `px */[
              25096,
              16
            ];
    } else {
      return /* `px */[
              25096,
              32
            ];
    }
  } else {
    return /* `px */[
            25096,
            24
          ];
  }
}

var ToCss = /* module */[/* spacing_to_css */spacing_to_css];

function Box(Props) {
  var children = Props.children;
  var p = Props.p;
  var px = Props.px;
  Props.py;
  var pl = Props.pl;
  Props.pr;
  Props.pt;
  Props.pb;
  var paddingLeft = pl !== undefined ? pl : (
      px !== undefined ? px : (
          p !== undefined ? p : undefined
        )
    );
  var leftResult = Belt_Option.mapWithDefault(paddingLeft, /* [] */0, (function (x) {
          if (typeof x === "number") {
            return /* :: */[
                    Css.paddingLeft(spacing_to_css(x)),
                    /* [] */0
                  ];
          } else {
            return Belt_List.mapWithIndex(x[1], (function (index, value) {
                          if (index !== 0) {
                            return Css.media("", /* :: */[
                                        Css.paddingLeft(spacing_to_css(value)),
                                        /* [] */0
                                      ]);
                          } else {
                            return Css.paddingLeft(spacing_to_css(value));
                          }
                        }));
          }
        }));
  return React.createElement("div", {
              className: Css.style(leftResult)
            }, children);
}

var make = Box;

exports.Theme = Theme;
exports.ToCss = ToCss;
exports.make = make;
/* Css Not a pure module */
