// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Box$ReactHooksTemplate = require("./Components/Box.bs.js");

function App(Props) {
  return React.createElement(Box$ReactHooksTemplate.make, {
              children: "hye"
            });
}

var make = App;

exports.make = make;
/* react Not a pure module */
