// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Box$ReactHooksTemplate = require("./Components/Box.bs.js");

function App(Props) {
  return React.createElement(Box$ReactHooksTemplate.make, {
              children: "hye",
              p: /* `mq */[
                24420,
                /* :: */[
                  /* xxl */5994348,
                  /* :: */[
                    /* xl */26868,
                    /* :: */[
                      /* m */109,
                      /* :: */[
                        /* xxs */5994355,
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            });
}

var make = App;

exports.make = make;
/* react Not a pure module */
